import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { eciesDecrypt } from "../src/ecies.js";

/**
 * Interop vector produced by **real go-ethereum** (`ecies.Encrypt` from go-ethereum v1.17.4, the
 * same version the FCC tee-node depends on) — generated by `fce-sigmax/go/cmd/ecies-interop`, which
 * also verified the reverse direction: geth's `Decrypt` successfully opened a ciphertext produced by
 * `src/ecies.ts`.
 *
 * This is the load-bearing proof that a signal encrypted in the leader's browser can be decrypted by
 * the enclave. If this test ever fails, the client-side encryption has diverged from the node and
 * every publish would be rejected inside the TEE.
 */
const vector = JSON.parse(
  readFileSync(fileURLToPath(new URL("./fixtures/geth-ecies-vector.json", import.meta.url)), "utf-8"),
) as { privateKey: string; ciphertext: string; expectedPlaintext: string };

function hexToBytes(hex: string): Uint8Array {
  const h = hex.slice(2);
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = Number.parseInt(h.slice(i * 2, i * 2 + 2), 16);
  return out;
}

describe("go-ethereum interop (ECIES_AES128_SHA256)", () => {
  it("decrypts a ciphertext produced by go-ethereum's ecies.Encrypt", () => {
    const plaintext = eciesDecrypt(hexToBytes(vector.privateKey), hexToBytes(vector.ciphertext));

    expect(`0x${Buffer.from(plaintext).toString("hex")}`).toBe(vector.expectedPlaintext);
    expect(new TextDecoder().decode(plaintext)).toBe("go-side-plaintext-for-reverse-interop");
  });

  it("rejects the geth vector under a tampered MAC", () => {
    const ct = hexToBytes(vector.ciphertext);
    ct[ct.length - 1]! ^= 0x01;

    expect(() => eciesDecrypt(hexToBytes(vector.privateKey), ct)).toThrow(/invalid MAC/);
  });
});
